// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYq0CTQFuP8Q7x0hAaEXgLO_87-QRvp_Q',
    appId: '1:820921726206:web:61d281340df88070ee61af',
    messagingSenderId: '820921726206',
    projectId: 'doandidong-69432',
    authDomain: 'doandidong-69432.firebaseapp.com',
    storageBucket: 'doandidong-69432.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdDdYihOvGRdQEDdHXNNyX05-JIteWbR4',
    appId: '1:820921726206:android:764d85be16af1c88ee61af',
    messagingSenderId: '820921726206',
    projectId: 'doandidong-69432',
    storageBucket: 'doandidong-69432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB77sX_2KA9VLIGWqwDw7fk6Ajmp4NvxA',
    appId: '1:820921726206:ios:636eb47391d57e57ee61af',
    messagingSenderId: '820921726206',
    projectId: 'doandidong-69432',
    storageBucket: 'doandidong-69432.appspot.com',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB77sX_2KA9VLIGWqwDw7fk6Ajmp4NvxA',
    appId: '1:820921726206:ios:636eb47391d57e57ee61af',
    messagingSenderId: '820921726206',
    projectId: 'doandidong-69432',
    storageBucket: 'doandidong-69432.appspot.com',
    iosBundleId: 'com.example.projectFlutter',
  );
}
